export const GAMES_LIST_REQUEST = "GAMES_LIST_REQUEST"
export const GAMES_LIST_SUCCESS = "GAMES_LIST_SUCCESS"
export const GAMES_LIST_FAIL = "GAMES_LIST_REQUEST"

export const SEARCH_GAMES_REQUEST = "SEARCH_GAMES_REQUEST"
export const SEARCH_GAMES_SUCCESS = "SEARCH_GAMES_SUCCESS"
export const SEARCH_GAMES_FAIL = "SEARCH_GAMES_FAIL"

export const FILTER_GAMES_REQUEST = "FILTER_GAMES_REQUEST"
export const FILTER_GAMES_SUCCESS = "FILTER_GAMES_SUCCESS"
export const FILTER_GAMES_FAIL = "FILTER_GAMES_FAIL"

export const GAME_DETAILS_REQUEST = "GAME_DETAILS_REQUEST"
export const GAME_DETAILS_SUCCESS = "GAME_DETAILS_SUCCESS"
export const GAME_DETAILS_FAIL = "GAME_DETAILS_FAIL"
